import{a as h,S as w,i as b}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&t(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function m(o,r){const a=new URLSearchParams({key:"43271859-59a58ad2885d01442ce560ecb",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:"15"});y();try{return(await h.get(`https://pixabay.com/api/?${a}`)).data}catch{throw new Error(response.status)}}async function f(o){if(o.hits.length===0)i(),p("Sorry, there are no images matching your search query. Please try again!");else{const a=o.hits.map(t=>`<li class="gallery-item">
                <a class="gallery-link" href="${t.largeImageURL}">
                  <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
                </a>
                <div class="stats">
                  <p class="text">Likes<br/>${t.likes}</p>
                  <p class="text">Views<br/>${t.views}</p>
                  <p class="text">Comments<br/>${t.comments}</p>
                  <p class="text">Downloads<br/>${t.downloads}</p>
                </div>
              </li>`).join("");n.gallery.insertAdjacentHTML("beforeend",a),g(),L.refresh()}}const n={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),wordInput:document.querySelector(".input"),loader:document.querySelector(".loader"),addButton:document.querySelector(".button")},L=new w(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7}),v=15;let c="",d=1;n.form.addEventListener("submit",S);n.addButton.addEventListener("click",B);l();i();async function S(o){o.preventDefault(),l(),y(),n.gallery.innerHTML="",c=n.wordInput.value.trim(),c!==""?await m(c,d).then(a=>{f(a),i()}).catch(a=>console.log(a)):(p("Please complete the field!"),i(),l()),n.form.reset();const r=n.wordInput.getBoundingClientRect();window.scrollBy({top:r.height*2+48,behavior:"smooth"})}async function B(o){o.preventDefault(),l(),y(),d+=1;const r=await m(c,d);if(d>=Math.ceil(r.totalHits/v))p("We're sorry, but you've reached the end of search results."),i(),l();else{f(r),i(),g();const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2+48,behavior:"smooth"})}}function p(o){b.error({title:"Error",message:o,position:"topRight"})}function y(){n.loader.style.display="block"}function i(){n.loader.style.display="none"}function g(){n.addButton.style.display="block"}function l(){n.addButton.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
